description:
  This section describes all of the services that may be present on the AP.
  Each service is then referenced via its name inside an interface, ssid, ...
type: object
properties:
  ssh:
    $ref: "https://uconfig.org/schema/v1/service/ssh/"
  mdns:
    $ref: "https://uconfig.org/schema/v1/service/mdns/"
  lldp:
    $ref: "https://uconfig.org/schema/v1/service/lldp/"
  ntp:
    $ref: "https://uconfig.org/schema/v1/service/ntp/"
  log:
    $ref: "https://uconfig.org/schema/v1/service/log/"
  ieee8021x:
    $ref: "https://uconfig.org/schema/v1/service/ieee8021x/"
