$id: https://uconfig.org/uconfig.schema.json
$schema: http://json-schema.org/draft-07/schema#
description: OpenWrt uconfig schema
type: object
properties:
  strict:
    description:
      The device will reject any configuration that causes warnings if strict mode is enabled.
    type: boolean
    default: false
  uuid:
    description:
      The unique ID of the configuration. This is the unix timestamp of when the config was created.
    type: integer
  unit:
    $ref: "https://uconfig.org/schema/v1/unit/"
  globals:
    $ref: "https://uconfig.org/schema/v1/globals/"
  ethernet:
    $ref: "https://uconfig.org/schema/v1/ethernet/"
  country-code:
    description:
      Specifies the country code, affects the available channels and
      transmission powers.
    type: string
    maxLength: 2
    minLength: 2
    examples:
    - US
  radios:
    type: object
    patternProperties:
      ".+":
        $ref: "https://uconfig.org/schema/v1/radio/"
        additionalProperties: false
  interfaces:
    type: object
    patternProperties:
      ".+":
        $ref: "https://uconfig.org/schema/v1/interface/"
        additionalProperties: false
  services:
    $ref: "https://uconfig.org/schema/v1/service/"
