#!/bin/sh /etc/rc.common

START=10

start() {
	[ -f /etc/uconfig/capabilities.json ] || /usr/libexec/uconfig/capabilities.uc

	mkdir -p /var/run/uci
	uconfig_apply -n /etc/uconfig/uconfig.active
	reload_config
}

stop() {
	rm -rf /var/run/uci
	reload_config
}
