backend UI {
	serve-directory /www/ {
		index-filename index.html;
		error-404-filename index.html;
		directory-listing false;
	}
}

backend webui {
	run-script /usr/share/ucode/uconfig/webui/uwsd-handler.uc;
}

listen :80 {
	match-path /uconfig {
		use-backend webui;
	}

	match-path /upload {
		use-backend webui;
	}

	match-protocol http {
		use-backend UI;
	}

	match-protocol ws {
		use-backend webui;
	}

	idle-timeout 120000;
}
