{%
	function generate_uconfig_ui_firewall_rules(interfaces) {
		if (!length(interfaces))
			return '';

		let output = [];

		uci_comment(output, '# generated by uconfig-ui.uc');
		uci_comment(output, '### generate uconfig-ui firewall rules');

		for (let interface in interfaces) {
			let name = interface.name;

			uci_section(output, 'firewall rule');
			uci_set_string(output, 'firewall.@rule[-1].name', `Allow-uconfig-ui-http-${name}`);
			uci_set_string(output, 'firewall.@rule[-1].src', name);
			uci_set_string(output, 'firewall.@rule[-1].dest_port', 80);
			uci_set_string(output, 'firewall.@rule[-1].proto', 'tcp');
			uci_set_string(output, 'firewall.@rule[-1].target', 'ACCEPT');
		}

		return uci_output(output);
	}

	let interfaces = services.lookup_interfaces("uconfig-ui");
	let enable = length(interfaces) > 0;

	services.set_enabled("uconfig-ui", enable);

	if (!enable)
		return;

	let conflict = port.claim('uconfig-ui', 80, 'tcp', interfaces);
	if (conflict) {
		state.strict = true;
		error('service port conflict: uconfig-ui port 80/tcp overlaps with %s on interface(s) %s',
		      conflict.service, join(', ', conflict.interfaces));
	}
%}

## Configure uconfig-ui firewall
{{ generate_uconfig_ui_firewall_rules(interfaces) }}
